# Generated by Django 4.2.7 on 2025-10-20 23:28

import chatbot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=chatbot.models.user_document_path)),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_content', models.TextField(blank=True, help_text='Extracted text from the document/image')),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='chatbot.chatmessage')),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
    ]
