# Generated by Django 4.2.7 on 2025-10-23 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0002_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session ID from the original chat', max_length=100, unique=True)),
                ('user_id', models.CharField(help_text='User session ID or user identifier', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending - User waiting for staff'), ('active', 'Active - Staff connected'), ('closed', 'Closed - Session ended')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connected_at', models.DateTimeField(blank=True, help_text='When staff connected', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When session was closed', null=True)),
                ('is_user_waiting_for_staff', models.BooleanField(default=False, help_text='Whether user requested staff help')),
                ('staff_member', models.ForeignKey(blank=True, help_text='ZRA staff member assigned to this chat', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealTimeChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'User Message'), ('staff', 'Staff Message'), ('system', 'System Notification')], max_length=10)),
                ('sender_id', models.CharField(help_text='ID of the sender (session ID for user, user ID for staff)', max_length=100)),
                ('message', models.TextField(help_text='Message content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether message has been read by the recipient')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_time_messages', to='chatbot.activechatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
